api:
  identifier: 'edgebound-backend'
  port: 3000

logger:
  options:
    level: trace

mongodb:
  url: 'mongodb://127.0.0.1:27017'
  database: 'edgebound'
  options:
    useUnifiedTopology: true
    useNewUrlParser: true